on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build react app
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build react app
        uses: docker://node:15.11.0-buster
        env:
          CI: false
        with:
          entrypoint: bash
          args: -c "npm install && npm run build"
      - name: Firebase deploy
        uses: docker://node:15.11.0-buster
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: "marta-1163a"
        with:
          entrypoint: bash
          args: -c "npm install -g firebase-tools && firebase deploy --token $FIREBASE_TOKEN --project $PROJECT_ID"